import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.1';

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type"
};

const handler = async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }
  try {
    const { table_name, operation, record_id, user_id, data } = await req.json();

    // Supabase admin client (service key)
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Get profile info (if available)
    let userInfo = null;
    if (user_id) {
      const { data: profile } = await supabase
        .from('profiles')
        .select('full_name, email, company_name, user_type')
        .eq('user_id', user_id)
        .single();
      userInfo = profile;
    }

    // Compose email
    const subject = `New ${operation} in ${table_name.replace('_', ' ').toUpperCase()} - RobotVerse`;
    let emailContent = `
      <h2>New ${operation} Notification</h2>
      <p><strong>Table:</strong> ${table_name}</p>
      <p><strong>Operation:</strong> ${operation}</p>
      <p><strong>Record ID:</strong> ${record_id}</p>
      <p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
    `;
    if (userInfo) {
      emailContent += `
        <h3>User Information:</h3>
        <p><strong>Name:</strong> ${userInfo.full_name || 'N/A'}</p>
        <p><strong>Email:</strong> ${userInfo.email || 'N/A'}</p>
        <p><strong>Company:</strong> ${userInfo.company_name || 'N/A'}</p>
        <p><strong>User Type:</strong> ${userInfo.user_type || 'N/A'}</p>
      `;
    }
    // Add record data section
    emailContent += `<h3>Record Details:</h3>`;
    switch (table_name) {
      case 'robots':
        emailContent += `
          <p><strong>Brand:</strong> ${data.brand || 'N/A'}</p>
          <p><strong>Model:</strong> ${data.model || 'N/A'}</p>
          <p><strong>Robot Type:</strong> ${data.robot_type || 'N/A'}</p>
          <p><strong>Price:</strong> ₹${data.price || 'N/A'}</p>
          <p><strong>Location:</strong> ${data.location || 'N/A'}</p>
        `;
        break;
      case 'spare_parts':
        emailContent += `
          <p><strong>Part Name:</strong> ${data.part_name || 'N/A'}</p>
          <p><strong>Category:</strong> ${data.category || 'N/A'}</p>
          <p><strong>Price:</strong> ₹${data.price || 'N/A'}</p>
          <p><strong>Quantity:</strong> ${data.quantity || 'N/A'}</p>
        `;
        break;
      case 'services':
        emailContent += `
          <p><strong>Service Type:</strong> ${data.service_type || 'N/A'}</p>
          <p><strong>Description:</strong> ${data.description || 'N/A'}</p>
          <p><strong>Price Range:</strong> ${data.price_range || 'N/A'}</p>
          <p><strong>Location:</strong> ${data.location || 'N/A'}</p>
        `;
        break;
      case 'logistics_services':
        emailContent += `
          <p><strong>Service Name:</strong> ${data.service_name || 'N/A'}</p>
          <p><strong>Service Type:</strong> ${data.service_type || 'N/A'}</p>
          <p><strong>Coverage Area:</strong> ${data.coverage_area || 'N/A'}</p>
          <p><strong>Price:</strong> ₹${data.price || 'N/A'}</p>
        `;
        break;
      case 'loan_products':
        emailContent += `
          <p><strong>Product Name:</strong> ${data.product_name || 'N/A'}</p>
          <p><strong>Interest Rate:</strong> ${data.interest_rate || 'N/A'}%</p>
          <p><strong>Max Amount:</strong> ₹${data.max_amount || 'N/A'}</p>
          <p><strong>Tenure:</strong> ${data.tenure_months || 'N/A'} months</p>
        `;
        break;
      case 'loan_schemes':
        emailContent += `
          <p><strong>Scheme Name:</strong> ${data.scheme_name || 'N/A'}</p>
          <p><strong>Interest Rate:</strong> ${data.interest_rate || 'N/A'}%</p>
          <p><strong>Max Amount:</strong> ₹${data.max_amount || 'N/A'}</p>
        `;
        break;
      default:
        emailContent += `<pre>${JSON.stringify(data, null, 2)}</pre>`;
    }
    emailContent += `
      <hr>
      <p><em>This notification was automatically generated by the RobotVerse system.</em></p>
      <p><a href="https://supabase.com/dashboard/project/cmahwgetrqczytnijbuk">View in Supabase Dashboard</a></p>
    `;

    // Send email via Resend
    const emailResponse = await resend.emails.send({
      from: "RobotVerse Admin <onboarding@resend.dev>",
      to: ["admin@robotverse.in"],
      subject: subject,
      html: emailContent
    });
    console.log("Admin notification sent successfully:", emailResponse);
    return new Response(JSON.stringify({
      success: true,
      emailResponse
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders
      }
    });
  } catch (error) {
    console.error("Error in send-admin-notification function:", error);
    return new Response(JSON.stringify({
      error: error.message
    }), {
      status: 500,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders
      }
    });
  }
};

serve(handler);
