import { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Loader2, Download, FileText, X } from 'lucide-react';
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

interface RobotReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  reportData: {
    report: string;
    robotData: any;
    timestamp: string;
  } | null;
  loading: boolean;
}

const RobotReportModal = ({ isOpen, onClose, reportData, loading }: RobotReportModalProps) => {
  const [downloading, setDownloading] = useState(false);

  const formatReportForDisplay = (report: string) => {
    // Split the report into sections and format for better readability
    const sections = report.split(/(?=\*\*[A-Z\s]+\*\*)/g).filter(section => section.trim());
    
    return sections.map((section, index) => {
      const lines = section.split('\n').filter(line => line.trim());
      const title = lines[0]?.replace(/\*\*/g, '') || '';
      const content = lines.slice(1).join('\n');
      
      return (
        <div key={index} className="mb-6">
          {title && (
            <h3 className="text-lg font-semibold text-foreground mb-3 border-b border-border pb-2">
              {title.replace(/^\d+\.\s*/, '')}
            </h3>
          )}
          <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
            {content}
          </div>
        </div>
      );
    });
  };

  const downloadAsPDF = async () => {
    if (!reportData) return;
    
    setDownloading(true);
    try {
      // Create a formatted HTML version for PDF conversion
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Robot Analysis Report - ${reportData.robotData.name}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            .header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
            .robot-info { background: #f5f5f5; padding: 20px; margin: 20px 0; border-radius: 8px; }
            .section { margin: 30px 0; }
            h1 { color: #333; margin-bottom: 10px; }
            h2 { color: #555; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
            h3 { color: #666; margin: 20px 0 10px 0; }
            .spec-list { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 10px 0; }
            .spec-item { padding: 5px 0; border-bottom: 1px dotted #ccc; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Robot Analysis Report</h1>
            <p><strong>Robot:</strong> ${reportData.robotData.name} - ${reportData.robotData.model}</p>
            <p><strong>Generated:</strong> ${new Date(reportData.timestamp).toLocaleString()}</p>
          </div>
          
          <div class="robot-info">
            <h2>Robot Overview</h2>
            <div class="spec-list">
              <div class="spec-item"><strong>Name:</strong> ${reportData.robotData.name}</div>
              <div class="spec-item"><strong>Model:</strong> ${reportData.robotData.model}</div>
              <div class="spec-item"><strong>Type:</strong> ${reportData.robotData.type}</div>
              <div class="spec-item"><strong>Brand:</strong> ${reportData.robotData.brand || 'Not specified'}</div>
              <div class="spec-item"><strong>Price:</strong> ${reportData.robotData.price ? `${reportData.robotData.currency} ${reportData.robotData.price}` : 'Price on request'}</div>
              <div class="spec-item"><strong>Location:</strong> ${reportData.robotData.location}</div>
            </div>
            ${reportData.robotData.description ? `<p><strong>Description:</strong> ${reportData.robotData.description}</p>` : ''}
          </div>
          
          <div class="section">
            ${reportData.report.replace(/\*\*(.*?)\*\*/g, '<h2>$1</h2>').replace(/\n/g, '<br>')}
          </div>
          
          <div class="footer">
            <p>Report generated by RoboVerse AI Analysis System</p>
          </div>
        </body>
        </html>
      `;

      // Create a blob and download
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `robot-report-${reportData.robotData.name.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
    } catch (error) {
      console.error('Error downloading report:', error);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] p-0">
        <DialogHeader className="p-6 pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-xl">Robot Analysis Report</DialogTitle>
                <DialogDescription>
                  {reportData?.robotData ? 
                    `${reportData.robotData.name} - ${reportData.robotData.model}` : 
                    'Comprehensive robot analysis'}
                </DialogDescription>
              </div>
            </div>
            <Button
              variant="ghost"
              size="icon"
              onClick={onClose}
              className="h-8 w-8"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
          
          {reportData?.robotData && (
            <div className="flex items-center gap-2 mt-4">
              <Badge variant="secondary">{reportData.robotData.type}</Badge>
              {reportData.robotData.brand && (
                <Badge variant="outline">{reportData.robotData.brand}</Badge>
              )}
              <Badge variant="outline">
                {reportData.robotData.price ? 
                  `${reportData.robotData.currency} ${reportData.robotData.price}` : 
                  'Price on request'}
              </Badge>
            </div>
          )}
        </DialogHeader>

        <Separator />

        <div className="flex-1 overflow-hidden">
          {loading ? (
            <div className="flex items-center justify-center h-64">
              <div className="text-center">
                <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
                <p className="text-muted-foreground">Generating comprehensive analysis report...</p>
                <p className="text-sm text-muted-foreground mt-2">This may take a few moments</p>
              </div>
            </div>
          ) : reportData ? (
            <ScrollArea className="h-[60vh] px-6">
              <div className="py-4">
                {formatReportForDisplay(reportData.report)}
              </div>
            </ScrollArea>
          ) : (
            <div className="flex items-center justify-center h-64">
              <p className="text-muted-foreground">No report data available</p>
            </div>
          )}
        </div>

        {reportData && !loading && (
          <>
            <Separator />
            <DialogFooter className="p-6">
              <div className="flex items-center justify-between w-full">
                <div className="text-sm text-muted-foreground">
                  Generated on {new Date(reportData.timestamp).toLocaleString()}
                </div>
                <div className="flex items-center gap-3">
                  <Button
                    variant="outline"
                    onClick={downloadAsPDF}
                    disabled={downloading}
                    className="flex items-center gap-2"
                  >
                    {downloading ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="h-4 w-4" />
                    )}
                    Download Report
                  </Button>
                  <Button onClick={onClose}>Close</Button>
                </div>
              </div>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default RobotReportModal;