/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyerGuideRouteImport } from './routes/buyer-guide'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileSettingsRouteImport } from './routes/profile-settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellerGuideRouteImport } from './routes/seller-guide'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SparePartsDashboardRouteImport } from './routes/spare-parts-dashboard'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestImageMigrationRouteImport } from './routes/test-image-migration'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as AuctionsCreateRouteImport } from './routes/auctions/create'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsIdRouteImport } from './routes/blogs/$id'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityIdRouteImport } from './routes/community/$id'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as DashboardCreditsRouteImport } from './routes/dashboard/credits'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardHelpRouteImport } from './routes/dashboard/help'
import { Route as DashboardLogisticsRouteImport } from './routes/dashboard/logistics'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMyRequestsRouteImport } from './routes/dashboard/my-requests'
import { Route as DashboardPartsRouteImport } from './routes/dashboard/parts'
import { Route as DashboardPrivacyRouteImport } from './routes/dashboard/privacy'
import { Route as DashboardQuotationsRouteImport } from './routes/dashboard/quotations'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardRobotsRouteImport } from './routes/dashboard/robots'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as FinancingIndexRouteImport } from './routes/financing/index'
import { Route as FinancingIdRouteImport } from './routes/financing/$id'
import { Route as LogisticsIndexRouteImport } from './routes/logistics/index'
import { Route as LogisticsIdRouteImport } from './routes/logistics/$id'
import { Route as MarketplacePartsRouteImport } from './routes/marketplace/parts'
import { Route as MarketplaceRobotsRouteImport } from './routes/marketplace/robots'
import { Route as MarketplaceServicesRouteImport } from './routes/marketplace/services'
import { Route as PartsIndexRouteImport } from './routes/parts/index'
import { Route as PartsIdRouteImport } from './routes/parts/$id'
import { Route as PreviewTokenRouteImport } from './routes/preview/$token'
import { Route as RobobookIndexRouteImport } from './routes/robobook/index'
import { Route as RobobookCreateRouteImport } from './routes/robobook/create'
import { Route as RobotTalentIndexRouteImport } from './routes/robot-talent/index'
import { Route as RobotTalentEmployerDashboardRouteImport } from './routes/robot-talent/employer-dashboard'
import { Route as RobotTalentPostJobRouteImport } from './routes/robot-talent/post-job'
import { Route as RobotTalentPostTrainingRouteImport } from './routes/robot-talent/post-training'
import { Route as RobotTalentSeekerProfileRouteImport } from './routes/robot-talent/seeker-profile'
import { Route as RobotsIndexRouteImport } from './routes/robots/index'
import { Route as RobotsIdRouteImport } from './routes/robots/$id'
import { Route as RobotsCompareRouteImport } from './routes/robots/compare'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesIdRouteImport } from './routes/services/$id'
import { Route as AuctionsIdIndexRouteImport } from './routes/auctions/$id/index'
import { Route as AuctionsIdEditRouteImport } from './routes/auctions/$id/edit'
import { Route as DashboardAdminSeoRouteImport } from './routes/dashboard/admin/seo'
import { Route as PartsBrandBrandRouteImport } from './routes/parts/brand/$brand'
import { Route as PartsCategoryCatRouteImport } from './routes/parts/category/$cat'
import { Route as RobobookIdIndexRouteImport } from './routes/robobook/$id/index'
import { Route as RobobookIdEditRouteImport } from './routes/robobook/$id/edit'
import { Route as RobotTalentJobsIdRouteImport } from './routes/robot-talent/jobs/$id'
import { Route as RobotsBrandUsedRouteImport } from './routes/robots/$brand/used'
import { Route as RobotsApplicationApplicationRouteImport } from './routes/robots/application/$application'
import { Route as RobotsBrandBrandRouteImport } from './routes/robots/brand/$brand'
import { Route as RobotsCityCityRouteImport } from './routes/robots/city/$city'
import { Route as SellerSellerIdRobotsRouteImport } from './routes/seller/$sellerId/robots'
import { Route as ServicesCityTypeRouteImport } from './routes/services/$city/$type'
import { Route as SparesCategoryIndexRouteImport } from './routes/spares/$category/index'
import { Route as SparesCategorySubcategoryIndexRouteImport } from './routes/spares/$category/$subcategory/index'
import { Route as SparesCategorySubcategoryComponentTypeRouteImport } from './routes/spares/$category/$subcategory/$componentType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerGuideRoute = BuyerGuideRouteImport.update({
  id: '/buyer-guide',
  path: '/buyer-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile-settings',
  path: '/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerGuideRoute = SellerGuideRouteImport.update({
  id: '/seller-guide',
  path: '/seller-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsDashboardRoute = SparePartsDashboardRouteImport.update({
  id: '/spare-parts-dashboard',
  path: '/spare-parts-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestImageMigrationRoute = TestImageMigrationRouteImport.update({
  id: '/test-image-migration',
  path: '/test-image-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsCreateRoute = AuctionsCreateRouteImport.update({
  id: '/auctions/create',
  path: '/auctions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/dashboard/api-keys',
  path: '/dashboard/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/dashboard/credits',
  path: '/dashboard/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/dashboard/finance',
  path: '/dashboard/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/dashboard/help',
  path: '/dashboard/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/dashboard/logistics',
  path: '/dashboard/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyRequestsRoute = DashboardMyRequestsRouteImport.update({
  id: '/dashboard/my-requests',
  path: '/dashboard/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPartsRoute = DashboardPartsRouteImport.update({
  id: '/dashboard/parts',
  path: '/dashboard/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: '/dashboard/privacy',
  path: '/dashboard/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuotationsRoute = DashboardQuotationsRouteImport.update({
  id: '/dashboard/quotations',
  path: '/dashboard/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRobotsRoute = DashboardRobotsRouteImport.update({
  id: '/dashboard/robots',
  path: '/dashboard/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/dashboard/services',
  path: '/dashboard/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingIndexRoute = FinancingIndexRouteImport.update({
  id: '/financing/',
  path: '/financing/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingIdRoute = FinancingIdRouteImport.update({
  id: '/financing/$id',
  path: '/financing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/logistics/',
  path: '/logistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIdRoute = LogisticsIdRouteImport.update({
  id: '/logistics/$id',
  path: '/logistics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePartsRoute = MarketplacePartsRouteImport.update({
  id: '/marketplace/parts',
  path: '/marketplace/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRobotsRoute = MarketplaceRobotsRouteImport.update({
  id: '/marketplace/robots',
  path: '/marketplace/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceServicesRoute = MarketplaceServicesRouteImport.update({
  id: '/marketplace/services',
  path: '/marketplace/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/parts/$id',
  path: '/parts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RobobookIndexRoute = RobobookIndexRouteImport.update({
  id: '/robobook/',
  path: '/robobook/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobobookCreateRoute = RobobookCreateRouteImport.update({
  id: '/robobook/create',
  path: '/robobook/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotTalentIndexRoute = RobotTalentIndexRouteImport.update({
  id: '/robot-talent/',
  path: '/robot-talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotTalentEmployerDashboardRoute =
  RobotTalentEmployerDashboardRouteImport.update({
    id: '/robot-talent/employer-dashboard',
    path: '/robot-talent/employer-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const RobotTalentPostJobRoute = RobotTalentPostJobRouteImport.update({
  id: '/robot-talent/post-job',
  path: '/robot-talent/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotTalentPostTrainingRoute = RobotTalentPostTrainingRouteImport.update({
  id: '/robot-talent/post-training',
  path: '/robot-talent/post-training',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotTalentSeekerProfileRoute =
  RobotTalentSeekerProfileRouteImport.update({
    id: '/robot-talent/seeker-profile',
    path: '/robot-talent/seeker-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const RobotsIndexRoute = RobotsIndexRouteImport.update({
  id: '/robots/',
  path: '/robots/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsIdRoute = RobotsIdRouteImport.update({
  id: '/robots/$id',
  path: '/robots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsCompareRoute = RobotsCompareRouteImport.update({
  id: '/robots/compare',
  path: '/robots/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdIndexRoute = AuctionsIdIndexRouteImport.update({
  id: '/auctions/$id/',
  path: '/auctions/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdEditRoute = AuctionsIdEditRouteImport.update({
  id: '/auctions/$id/edit',
  path: '/auctions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSeoRoute = DashboardAdminSeoRouteImport.update({
  id: '/dashboard/admin/seo',
  path: '/dashboard/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsBrandBrandRoute = PartsBrandBrandRouteImport.update({
  id: '/parts/brand/$brand',
  path: '/parts/brand/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsCategoryCatRoute = PartsCategoryCatRouteImport.update({
  id: '/parts/category/$cat',
  path: '/parts/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const RobobookIdIndexRoute = RobobookIdIndexRouteImport.update({
  id: '/robobook/$id/',
  path: '/robobook/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobobookIdEditRoute = RobobookIdEditRouteImport.update({
  id: '/robobook/$id/edit',
  path: '/robobook/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotTalentJobsIdRoute = RobotTalentJobsIdRouteImport.update({
  id: '/robot-talent/jobs/$id',
  path: '/robot-talent/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsBrandUsedRoute = RobotsBrandUsedRouteImport.update({
  id: '/robots/$brand/used',
  path: '/robots/$brand/used',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsApplicationApplicationRoute =
  RobotsApplicationApplicationRouteImport.update({
    id: '/robots/application/$application',
    path: '/robots/application/$application',
    getParentRoute: () => rootRouteImport,
  } as any)
const RobotsBrandBrandRoute = RobotsBrandBrandRouteImport.update({
  id: '/robots/brand/$brand',
  path: '/robots/brand/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsCityCityRoute = RobotsCityCityRouteImport.update({
  id: '/robots/city/$city',
  path: '/robots/city/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIdRobotsRoute = SellerSellerIdRobotsRouteImport.update({
  id: '/seller/$sellerId/robots',
  path: '/seller/$sellerId/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCityTypeRoute = ServicesCityTypeRouteImport.update({
  id: '/services/$city/$type',
  path: '/services/$city/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const SparesCategoryIndexRoute = SparesCategoryIndexRouteImport.update({
  id: '/spares/$category/',
  path: '/spares/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const SparesCategorySubcategoryIndexRoute =
  SparesCategorySubcategoryIndexRouteImport.update({
    id: '/spares/$category/$subcategory/',
    path: '/spares/$category/$subcategory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparesCategorySubcategoryComponentTypeRoute =
  SparesCategorySubcategoryComponentTypeRouteImport.update({
    id: '/spares/$category/$subcategory/$componentType',
    path: '/spares/$category/$subcategory/$componentType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/pricing': typeof PricingRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guide': typeof SellerGuideRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/spare-parts-dashboard': typeof SparePartsDashboardRoute
  '/terms': typeof TermsRoute
  '/test-image-migration': typeof TestImageMigrationRoute
  '/watchlist': typeof WatchlistRoute
  '/auctions/create': typeof AuctionsCreateRoute
  '/blog/$id': typeof BlogIdRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/community/$id': typeof CommunityIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-requests': typeof DashboardMyRequestsRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/quotations': typeof DashboardQuotationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/financing/$id': typeof FinancingIdRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/marketplace/parts': typeof MarketplacePartsRoute
  '/marketplace/robots': typeof MarketplaceRobotsRoute
  '/marketplace/services': typeof MarketplaceServicesRoute
  '/parts/$id': typeof PartsIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/robobook/create': typeof RobobookCreateRoute
  '/robot-talent/employer-dashboard': typeof RobotTalentEmployerDashboardRoute
  '/robot-talent/post-job': typeof RobotTalentPostJobRoute
  '/robot-talent/post-training': typeof RobotTalentPostTrainingRoute
  '/robot-talent/seeker-profile': typeof RobotTalentSeekerProfileRoute
  '/robots/$id': typeof RobotsIdRoute
  '/robots/compare': typeof RobotsCompareRoute
  '/services/$id': typeof ServicesIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/financing/': typeof FinancingIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/robobook/': typeof RobobookIndexRoute
  '/robot-talent/': typeof RobotTalentIndexRoute
  '/robots/': typeof RobotsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/auctions/$id/edit': typeof AuctionsIdEditRoute
  '/dashboard/admin/seo': typeof DashboardAdminSeoRoute
  '/parts/brand/$brand': typeof PartsBrandBrandRoute
  '/parts/category/$cat': typeof PartsCategoryCatRoute
  '/robobook/$id/edit': typeof RobobookIdEditRoute
  '/robot-talent/jobs/$id': typeof RobotTalentJobsIdRoute
  '/robots/$brand/used': typeof RobotsBrandUsedRoute
  '/robots/application/$application': typeof RobotsApplicationApplicationRoute
  '/robots/brand/$brand': typeof RobotsBrandBrandRoute
  '/robots/city/$city': typeof RobotsCityCityRoute
  '/seller/$sellerId/robots': typeof SellerSellerIdRobotsRoute
  '/services/$city/$type': typeof ServicesCityTypeRoute
  '/auctions/$id/': typeof AuctionsIdIndexRoute
  '/robobook/$id/': typeof RobobookIdIndexRoute
  '/spares/$category/': typeof SparesCategoryIndexRoute
  '/spares/$category/$subcategory/$componentType': typeof SparesCategorySubcategoryComponentTypeRoute
  '/spares/$category/$subcategory/': typeof SparesCategorySubcategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/pricing': typeof PricingRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guide': typeof SellerGuideRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/spare-parts-dashboard': typeof SparePartsDashboardRoute
  '/terms': typeof TermsRoute
  '/test-image-migration': typeof TestImageMigrationRoute
  '/watchlist': typeof WatchlistRoute
  '/auctions/create': typeof AuctionsCreateRoute
  '/blog/$id': typeof BlogIdRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/community/$id': typeof CommunityIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-requests': typeof DashboardMyRequestsRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/quotations': typeof DashboardQuotationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/financing/$id': typeof FinancingIdRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/marketplace/parts': typeof MarketplacePartsRoute
  '/marketplace/robots': typeof MarketplaceRobotsRoute
  '/marketplace/services': typeof MarketplaceServicesRoute
  '/parts/$id': typeof PartsIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/robobook/create': typeof RobobookCreateRoute
  '/robot-talent/employer-dashboard': typeof RobotTalentEmployerDashboardRoute
  '/robot-talent/post-job': typeof RobotTalentPostJobRoute
  '/robot-talent/post-training': typeof RobotTalentPostTrainingRoute
  '/robot-talent/seeker-profile': typeof RobotTalentSeekerProfileRoute
  '/robots/$id': typeof RobotsIdRoute
  '/robots/compare': typeof RobotsCompareRoute
  '/services/$id': typeof ServicesIdRoute
  '/auctions': typeof AuctionsIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/community': typeof CommunityIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/financing': typeof FinancingIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/parts': typeof PartsIndexRoute
  '/robobook': typeof RobobookIndexRoute
  '/robot-talent': typeof RobotTalentIndexRoute
  '/robots': typeof RobotsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/auctions/$id/edit': typeof AuctionsIdEditRoute
  '/dashboard/admin/seo': typeof DashboardAdminSeoRoute
  '/parts/brand/$brand': typeof PartsBrandBrandRoute
  '/parts/category/$cat': typeof PartsCategoryCatRoute
  '/robobook/$id/edit': typeof RobobookIdEditRoute
  '/robot-talent/jobs/$id': typeof RobotTalentJobsIdRoute
  '/robots/$brand/used': typeof RobotsBrandUsedRoute
  '/robots/application/$application': typeof RobotsApplicationApplicationRoute
  '/robots/brand/$brand': typeof RobotsBrandBrandRoute
  '/robots/city/$city': typeof RobotsCityCityRoute
  '/seller/$sellerId/robots': typeof SellerSellerIdRobotsRoute
  '/services/$city/$type': typeof ServicesCityTypeRoute
  '/auctions/$id': typeof AuctionsIdIndexRoute
  '/robobook/$id': typeof RobobookIdIndexRoute
  '/spares/$category': typeof SparesCategoryIndexRoute
  '/spares/$category/$subcategory/$componentType': typeof SparesCategorySubcategoryComponentTypeRoute
  '/spares/$category/$subcategory': typeof SparesCategorySubcategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/pricing': typeof PricingRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guide': typeof SellerGuideRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/spare-parts-dashboard': typeof SparePartsDashboardRoute
  '/terms': typeof TermsRoute
  '/test-image-migration': typeof TestImageMigrationRoute
  '/watchlist': typeof WatchlistRoute
  '/auctions/create': typeof AuctionsCreateRoute
  '/blog/$id': typeof BlogIdRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/community/$id': typeof CommunityIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-requests': typeof DashboardMyRequestsRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/quotations': typeof DashboardQuotationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/financing/$id': typeof FinancingIdRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/marketplace/parts': typeof MarketplacePartsRoute
  '/marketplace/robots': typeof MarketplaceRobotsRoute
  '/marketplace/services': typeof MarketplaceServicesRoute
  '/parts/$id': typeof PartsIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/robobook/create': typeof RobobookCreateRoute
  '/robot-talent/employer-dashboard': typeof RobotTalentEmployerDashboardRoute
  '/robot-talent/post-job': typeof RobotTalentPostJobRoute
  '/robot-talent/post-training': typeof RobotTalentPostTrainingRoute
  '/robot-talent/seeker-profile': typeof RobotTalentSeekerProfileRoute
  '/robots/$id': typeof RobotsIdRoute
  '/robots/compare': typeof RobotsCompareRoute
  '/services/$id': typeof ServicesIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/financing/': typeof FinancingIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/robobook/': typeof RobobookIndexRoute
  '/robot-talent/': typeof RobotTalentIndexRoute
  '/robots/': typeof RobotsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/auctions/$id/edit': typeof AuctionsIdEditRoute
  '/dashboard/admin/seo': typeof DashboardAdminSeoRoute
  '/parts/brand/$brand': typeof PartsBrandBrandRoute
  '/parts/category/$cat': typeof PartsCategoryCatRoute
  '/robobook/$id/edit': typeof RobobookIdEditRoute
  '/robot-talent/jobs/$id': typeof RobotTalentJobsIdRoute
  '/robots/$brand/used': typeof RobotsBrandUsedRoute
  '/robots/application/$application': typeof RobotsApplicationApplicationRoute
  '/robots/brand/$brand': typeof RobotsBrandBrandRoute
  '/robots/city/$city': typeof RobotsCityCityRoute
  '/seller/$sellerId/robots': typeof SellerSellerIdRobotsRoute
  '/services/$city/$type': typeof ServicesCityTypeRoute
  '/auctions/$id/': typeof AuctionsIdIndexRoute
  '/robobook/$id/': typeof RobobookIdIndexRoute
  '/spares/$category/': typeof SparesCategoryIndexRoute
  '/spares/$category/$subcategory/$componentType': typeof SparesCategorySubcategoryComponentTypeRoute
  '/spares/$category/$subcategory/': typeof SparesCategorySubcategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/api-docs'
    | '/auth'
    | '/buyer-guide'
    | '/chat'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/pricing'
    | '/profile-settings'
    | '/reset-password'
    | '/seller-guide'
    | '/settings'
    | '/sitemap'
    | '/spare-parts-dashboard'
    | '/terms'
    | '/test-image-migration'
    | '/watchlist'
    | '/auctions/create'
    | '/blog/$id'
    | '/blogs/$id'
    | '/community/$id'
    | '/compare/$slug'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/credits'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/logistics'
    | '/dashboard/messages'
    | '/dashboard/my-requests'
    | '/dashboard/parts'
    | '/dashboard/privacy'
    | '/dashboard/quotations'
    | '/dashboard/reports'
    | '/dashboard/robots'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/financing/$id'
    | '/logistics/$id'
    | '/marketplace/parts'
    | '/marketplace/robots'
    | '/marketplace/services'
    | '/parts/$id'
    | '/preview/$token'
    | '/robobook/create'
    | '/robot-talent/employer-dashboard'
    | '/robot-talent/post-job'
    | '/robot-talent/post-training'
    | '/robot-talent/seeker-profile'
    | '/robots/$id'
    | '/robots/compare'
    | '/services/$id'
    | '/auctions/'
    | '/blogs/'
    | '/community/'
    | '/dashboard/'
    | '/financing/'
    | '/logistics/'
    | '/parts/'
    | '/robobook/'
    | '/robot-talent/'
    | '/robots/'
    | '/services/'
    | '/auctions/$id/edit'
    | '/dashboard/admin/seo'
    | '/parts/brand/$brand'
    | '/parts/category/$cat'
    | '/robobook/$id/edit'
    | '/robot-talent/jobs/$id'
    | '/robots/$brand/used'
    | '/robots/application/$application'
    | '/robots/brand/$brand'
    | '/robots/city/$city'
    | '/seller/$sellerId/robots'
    | '/services/$city/$type'
    | '/auctions/$id/'
    | '/robobook/$id/'
    | '/spares/$category/'
    | '/spares/$category/$subcategory/$componentType'
    | '/spares/$category/$subcategory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/api-docs'
    | '/auth'
    | '/buyer-guide'
    | '/chat'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/pricing'
    | '/profile-settings'
    | '/reset-password'
    | '/seller-guide'
    | '/settings'
    | '/sitemap'
    | '/spare-parts-dashboard'
    | '/terms'
    | '/test-image-migration'
    | '/watchlist'
    | '/auctions/create'
    | '/blog/$id'
    | '/blogs/$id'
    | '/community/$id'
    | '/compare/$slug'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/credits'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/logistics'
    | '/dashboard/messages'
    | '/dashboard/my-requests'
    | '/dashboard/parts'
    | '/dashboard/privacy'
    | '/dashboard/quotations'
    | '/dashboard/reports'
    | '/dashboard/robots'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/financing/$id'
    | '/logistics/$id'
    | '/marketplace/parts'
    | '/marketplace/robots'
    | '/marketplace/services'
    | '/parts/$id'
    | '/preview/$token'
    | '/robobook/create'
    | '/robot-talent/employer-dashboard'
    | '/robot-talent/post-job'
    | '/robot-talent/post-training'
    | '/robot-talent/seeker-profile'
    | '/robots/$id'
    | '/robots/compare'
    | '/services/$id'
    | '/auctions'
    | '/blogs'
    | '/community'
    | '/dashboard'
    | '/financing'
    | '/logistics'
    | '/parts'
    | '/robobook'
    | '/robot-talent'
    | '/robots'
    | '/services'
    | '/auctions/$id/edit'
    | '/dashboard/admin/seo'
    | '/parts/brand/$brand'
    | '/parts/category/$cat'
    | '/robobook/$id/edit'
    | '/robot-talent/jobs/$id'
    | '/robots/$brand/used'
    | '/robots/application/$application'
    | '/robots/brand/$brand'
    | '/robots/city/$city'
    | '/seller/$sellerId/robots'
    | '/services/$city/$type'
    | '/auctions/$id'
    | '/robobook/$id'
    | '/spares/$category'
    | '/spares/$category/$subcategory/$componentType'
    | '/spares/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/api-docs'
    | '/auth'
    | '/buyer-guide'
    | '/chat'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/pricing'
    | '/profile-settings'
    | '/reset-password'
    | '/seller-guide'
    | '/settings'
    | '/sitemap'
    | '/spare-parts-dashboard'
    | '/terms'
    | '/test-image-migration'
    | '/watchlist'
    | '/auctions/create'
    | '/blog/$id'
    | '/blogs/$id'
    | '/community/$id'
    | '/compare/$slug'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/credits'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/logistics'
    | '/dashboard/messages'
    | '/dashboard/my-requests'
    | '/dashboard/parts'
    | '/dashboard/privacy'
    | '/dashboard/quotations'
    | '/dashboard/reports'
    | '/dashboard/robots'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/financing/$id'
    | '/logistics/$id'
    | '/marketplace/parts'
    | '/marketplace/robots'
    | '/marketplace/services'
    | '/parts/$id'
    | '/preview/$token'
    | '/robobook/create'
    | '/robot-talent/employer-dashboard'
    | '/robot-talent/post-job'
    | '/robot-talent/post-training'
    | '/robot-talent/seeker-profile'
    | '/robots/$id'
    | '/robots/compare'
    | '/services/$id'
    | '/auctions/'
    | '/blogs/'
    | '/community/'
    | '/dashboard/'
    | '/financing/'
    | '/logistics/'
    | '/parts/'
    | '/robobook/'
    | '/robot-talent/'
    | '/robots/'
    | '/services/'
    | '/auctions/$id/edit'
    | '/dashboard/admin/seo'
    | '/parts/brand/$brand'
    | '/parts/category/$cat'
    | '/robobook/$id/edit'
    | '/robot-talent/jobs/$id'
    | '/robots/$brand/used'
    | '/robots/application/$application'
    | '/robots/brand/$brand'
    | '/robots/city/$city'
    | '/seller/$sellerId/robots'
    | '/services/$city/$type'
    | '/auctions/$id/'
    | '/robobook/$id/'
    | '/spares/$category/'
    | '/spares/$category/$subcategory/$componentType'
    | '/spares/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AiAssistantRoute: typeof AiAssistantRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  BuyerGuideRoute: typeof BuyerGuideRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CrmRoute: typeof CrmRoute
  PricingRoute: typeof PricingRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerGuideRoute: typeof SellerGuideRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
  SparePartsDashboardRoute: typeof SparePartsDashboardRoute
  TermsRoute: typeof TermsRoute
  TestImageMigrationRoute: typeof TestImageMigrationRoute
  WatchlistRoute: typeof WatchlistRoute
  AuctionsCreateRoute: typeof AuctionsCreateRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogsIdRoute: typeof BlogsIdRoute
  CommunityIdRoute: typeof CommunityIdRoute
  CompareSlugRoute: typeof CompareSlugRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLogisticsRoute: typeof DashboardLogisticsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyRequestsRoute: typeof DashboardMyRequestsRoute
  DashboardPartsRoute: typeof DashboardPartsRoute
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute
  DashboardQuotationsRoute: typeof DashboardQuotationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRobotsRoute: typeof DashboardRobotsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  FinancingIdRoute: typeof FinancingIdRoute
  LogisticsIdRoute: typeof LogisticsIdRoute
  MarketplacePartsRoute: typeof MarketplacePartsRoute
  MarketplaceRobotsRoute: typeof MarketplaceRobotsRoute
  MarketplaceServicesRoute: typeof MarketplaceServicesRoute
  PartsIdRoute: typeof PartsIdRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
  RobobookCreateRoute: typeof RobobookCreateRoute
  RobotTalentEmployerDashboardRoute: typeof RobotTalentEmployerDashboardRoute
  RobotTalentPostJobRoute: typeof RobotTalentPostJobRoute
  RobotTalentPostTrainingRoute: typeof RobotTalentPostTrainingRoute
  RobotTalentSeekerProfileRoute: typeof RobotTalentSeekerProfileRoute
  RobotsIdRoute: typeof RobotsIdRoute
  RobotsCompareRoute: typeof RobotsCompareRoute
  ServicesIdRoute: typeof ServicesIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FinancingIndexRoute: typeof FinancingIndexRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
  PartsIndexRoute: typeof PartsIndexRoute
  RobobookIndexRoute: typeof RobobookIndexRoute
  RobotTalentIndexRoute: typeof RobotTalentIndexRoute
  RobotsIndexRoute: typeof RobotsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AuctionsIdEditRoute: typeof AuctionsIdEditRoute
  DashboardAdminSeoRoute: typeof DashboardAdminSeoRoute
  PartsBrandBrandRoute: typeof PartsBrandBrandRoute
  PartsCategoryCatRoute: typeof PartsCategoryCatRoute
  RobobookIdEditRoute: typeof RobobookIdEditRoute
  RobotTalentJobsIdRoute: typeof RobotTalentJobsIdRoute
  RobotsBrandUsedRoute: typeof RobotsBrandUsedRoute
  RobotsApplicationApplicationRoute: typeof RobotsApplicationApplicationRoute
  RobotsBrandBrandRoute: typeof RobotsBrandBrandRoute
  RobotsCityCityRoute: typeof RobotsCityCityRoute
  SellerSellerIdRobotsRoute: typeof SellerSellerIdRobotsRoute
  ServicesCityTypeRoute: typeof ServicesCityTypeRoute
  AuctionsIdIndexRoute: typeof AuctionsIdIndexRoute
  RobobookIdIndexRoute: typeof RobobookIdIndexRoute
  SparesCategoryIndexRoute: typeof SparesCategoryIndexRoute
  SparesCategorySubcategoryComponentTypeRoute: typeof SparesCategorySubcategoryComponentTypeRoute
  SparesCategorySubcategoryIndexRoute: typeof SparesCategorySubcategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-guide': {
      id: '/buyer-guide'
      path: '/buyer-guide'
      fullPath: '/buyer-guide'
      preLoaderRoute: typeof BuyerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-guide': {
      id: '/seller-guide'
      path: '/seller-guide'
      fullPath: '/seller-guide'
      preLoaderRoute: typeof SellerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts-dashboard': {
      id: '/spare-parts-dashboard'
      path: '/spare-parts-dashboard'
      fullPath: '/spare-parts-dashboard'
      preLoaderRoute: typeof SparePartsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-image-migration': {
      id: '/test-image-migration'
      path: '/test-image-migration'
      fullPath: '/test-image-migration'
      preLoaderRoute: typeof TestImageMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/create': {
      id: '/auctions/create'
      path: '/auctions/create'
      fullPath: '/auctions/create'
      preLoaderRoute: typeof AuctionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/credits': {
      id: '/dashboard/credits'
      path: '/dashboard/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/dashboard/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/dashboard/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/logistics': {
      id: '/dashboard/logistics'
      path: '/dashboard/logistics'
      fullPath: '/dashboard/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-requests': {
      id: '/dashboard/my-requests'
      path: '/dashboard/my-requests'
      fullPath: '/dashboard/my-requests'
      preLoaderRoute: typeof DashboardMyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parts': {
      id: '/dashboard/parts'
      path: '/dashboard/parts'
      fullPath: '/dashboard/parts'
      preLoaderRoute: typeof DashboardPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/privacy': {
      id: '/dashboard/privacy'
      path: '/dashboard/privacy'
      fullPath: '/dashboard/privacy'
      preLoaderRoute: typeof DashboardPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotations': {
      id: '/dashboard/quotations'
      path: '/dashboard/quotations'
      fullPath: '/dashboard/quotations'
      preLoaderRoute: typeof DashboardQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/robots': {
      id: '/dashboard/robots'
      path: '/dashboard/robots'
      fullPath: '/dashboard/robots'
      preLoaderRoute: typeof DashboardRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/dashboard/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing/': {
      id: '/financing/'
      path: '/financing'
      fullPath: '/financing/'
      preLoaderRoute: typeof FinancingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing/$id': {
      id: '/financing/$id'
      path: '/financing/$id'
      fullPath: '/financing/$id'
      preLoaderRoute: typeof FinancingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/logistics'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/$id': {
      id: '/logistics/$id'
      path: '/logistics/$id'
      fullPath: '/logistics/$id'
      preLoaderRoute: typeof LogisticsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/parts': {
      id: '/marketplace/parts'
      path: '/marketplace/parts'
      fullPath: '/marketplace/parts'
      preLoaderRoute: typeof MarketplacePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/robots': {
      id: '/marketplace/robots'
      path: '/marketplace/robots'
      fullPath: '/marketplace/robots'
      preLoaderRoute: typeof MarketplaceRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/services': {
      id: '/marketplace/services'
      path: '/marketplace/services'
      fullPath: '/marketplace/services'
      preLoaderRoute: typeof MarketplaceServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/': {
      id: '/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/parts/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robobook/': {
      id: '/robobook/'
      path: '/robobook'
      fullPath: '/robobook/'
      preLoaderRoute: typeof RobobookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robobook/create': {
      id: '/robobook/create'
      path: '/robobook/create'
      fullPath: '/robobook/create'
      preLoaderRoute: typeof RobobookCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/': {
      id: '/robot-talent/'
      path: '/robot-talent'
      fullPath: '/robot-talent/'
      preLoaderRoute: typeof RobotTalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/employer-dashboard': {
      id: '/robot-talent/employer-dashboard'
      path: '/robot-talent/employer-dashboard'
      fullPath: '/robot-talent/employer-dashboard'
      preLoaderRoute: typeof RobotTalentEmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/post-job': {
      id: '/robot-talent/post-job'
      path: '/robot-talent/post-job'
      fullPath: '/robot-talent/post-job'
      preLoaderRoute: typeof RobotTalentPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/post-training': {
      id: '/robot-talent/post-training'
      path: '/robot-talent/post-training'
      fullPath: '/robot-talent/post-training'
      preLoaderRoute: typeof RobotTalentPostTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/seeker-profile': {
      id: '/robot-talent/seeker-profile'
      path: '/robot-talent/seeker-profile'
      fullPath: '/robot-talent/seeker-profile'
      preLoaderRoute: typeof RobotTalentSeekerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/': {
      id: '/robots/'
      path: '/robots'
      fullPath: '/robots/'
      preLoaderRoute: typeof RobotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/$id': {
      id: '/robots/$id'
      path: '/robots/$id'
      fullPath: '/robots/$id'
      preLoaderRoute: typeof RobotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/compare': {
      id: '/robots/compare'
      path: '/robots/compare'
      fullPath: '/robots/compare'
      preLoaderRoute: typeof RobotsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id/': {
      id: '/auctions/$id/'
      path: '/auctions/$id'
      fullPath: '/auctions/$id/'
      preLoaderRoute: typeof AuctionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id/edit': {
      id: '/auctions/$id/edit'
      path: '/auctions/$id/edit'
      fullPath: '/auctions/$id/edit'
      preLoaderRoute: typeof AuctionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/seo': {
      id: '/dashboard/admin/seo'
      path: '/dashboard/admin/seo'
      fullPath: '/dashboard/admin/seo'
      preLoaderRoute: typeof DashboardAdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/brand/$brand': {
      id: '/parts/brand/$brand'
      path: '/parts/brand/$brand'
      fullPath: '/parts/brand/$brand'
      preLoaderRoute: typeof PartsBrandBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/category/$cat': {
      id: '/parts/category/$cat'
      path: '/parts/category/$cat'
      fullPath: '/parts/category/$cat'
      preLoaderRoute: typeof PartsCategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robobook/$id/': {
      id: '/robobook/$id/'
      path: '/robobook/$id'
      fullPath: '/robobook/$id/'
      preLoaderRoute: typeof RobobookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robobook/$id/edit': {
      id: '/robobook/$id/edit'
      path: '/robobook/$id/edit'
      fullPath: '/robobook/$id/edit'
      preLoaderRoute: typeof RobobookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot-talent/jobs/$id': {
      id: '/robot-talent/jobs/$id'
      path: '/robot-talent/jobs/$id'
      fullPath: '/robot-talent/jobs/$id'
      preLoaderRoute: typeof RobotTalentJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/$brand/used': {
      id: '/robots/$brand/used'
      path: '/robots/$brand/used'
      fullPath: '/robots/$brand/used'
      preLoaderRoute: typeof RobotsBrandUsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/application/$application': {
      id: '/robots/application/$application'
      path: '/robots/application/$application'
      fullPath: '/robots/application/$application'
      preLoaderRoute: typeof RobotsApplicationApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/brand/$brand': {
      id: '/robots/brand/$brand'
      path: '/robots/brand/$brand'
      fullPath: '/robots/brand/$brand'
      preLoaderRoute: typeof RobotsBrandBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/city/$city': {
      id: '/robots/city/$city'
      path: '/robots/city/$city'
      fullPath: '/robots/city/$city'
      preLoaderRoute: typeof RobotsCityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$sellerId/robots': {
      id: '/seller/$sellerId/robots'
      path: '/seller/$sellerId/robots'
      fullPath: '/seller/$sellerId/robots'
      preLoaderRoute: typeof SellerSellerIdRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$city/$type': {
      id: '/services/$city/$type'
      path: '/services/$city/$type'
      fullPath: '/services/$city/$type'
      preLoaderRoute: typeof ServicesCityTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares/$category/': {
      id: '/spares/$category/'
      path: '/spares/$category'
      fullPath: '/spares/$category/'
      preLoaderRoute: typeof SparesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares/$category/$subcategory/': {
      id: '/spares/$category/$subcategory/'
      path: '/spares/$category/$subcategory'
      fullPath: '/spares/$category/$subcategory/'
      preLoaderRoute: typeof SparesCategorySubcategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares/$category/$subcategory/$componentType': {
      id: '/spares/$category/$subcategory/$componentType'
      path: '/spares/$category/$subcategory/$componentType'
      fullPath: '/spares/$category/$subcategory/$componentType'
      preLoaderRoute: typeof SparesCategorySubcategoryComponentTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AiAssistantRoute: AiAssistantRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  BuyerGuideRoute: BuyerGuideRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CrmRoute: CrmRoute,
  PricingRoute: PricingRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerGuideRoute: SellerGuideRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
  SparePartsDashboardRoute: SparePartsDashboardRoute,
  TermsRoute: TermsRoute,
  TestImageMigrationRoute: TestImageMigrationRoute,
  WatchlistRoute: WatchlistRoute,
  AuctionsCreateRoute: AuctionsCreateRoute,
  BlogIdRoute: BlogIdRoute,
  BlogsIdRoute: BlogsIdRoute,
  CommunityIdRoute: CommunityIdRoute,
  CompareSlugRoute: CompareSlugRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLogisticsRoute: DashboardLogisticsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyRequestsRoute: DashboardMyRequestsRoute,
  DashboardPartsRoute: DashboardPartsRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardQuotationsRoute: DashboardQuotationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRobotsRoute: DashboardRobotsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  FinancingIdRoute: FinancingIdRoute,
  LogisticsIdRoute: LogisticsIdRoute,
  MarketplacePartsRoute: MarketplacePartsRoute,
  MarketplaceRobotsRoute: MarketplaceRobotsRoute,
  MarketplaceServicesRoute: MarketplaceServicesRoute,
  PartsIdRoute: PartsIdRoute,
  PreviewTokenRoute: PreviewTokenRoute,
  RobobookCreateRoute: RobobookCreateRoute,
  RobotTalentEmployerDashboardRoute: RobotTalentEmployerDashboardRoute,
  RobotTalentPostJobRoute: RobotTalentPostJobRoute,
  RobotTalentPostTrainingRoute: RobotTalentPostTrainingRoute,
  RobotTalentSeekerProfileRoute: RobotTalentSeekerProfileRoute,
  RobotsIdRoute: RobotsIdRoute,
  RobotsCompareRoute: RobotsCompareRoute,
  ServicesIdRoute: ServicesIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FinancingIndexRoute: FinancingIndexRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
  PartsIndexRoute: PartsIndexRoute,
  RobobookIndexRoute: RobobookIndexRoute,
  RobotTalentIndexRoute: RobotTalentIndexRoute,
  RobotsIndexRoute: RobotsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AuctionsIdEditRoute: AuctionsIdEditRoute,
  DashboardAdminSeoRoute: DashboardAdminSeoRoute,
  PartsBrandBrandRoute: PartsBrandBrandRoute,
  PartsCategoryCatRoute: PartsCategoryCatRoute,
  RobobookIdEditRoute: RobobookIdEditRoute,
  RobotTalentJobsIdRoute: RobotTalentJobsIdRoute,
  RobotsBrandUsedRoute: RobotsBrandUsedRoute,
  RobotsApplicationApplicationRoute: RobotsApplicationApplicationRoute,
  RobotsBrandBrandRoute: RobotsBrandBrandRoute,
  RobotsCityCityRoute: RobotsCityCityRoute,
  SellerSellerIdRobotsRoute: SellerSellerIdRobotsRoute,
  ServicesCityTypeRoute: ServicesCityTypeRoute,
  AuctionsIdIndexRoute: AuctionsIdIndexRoute,
  RobobookIdIndexRoute: RobobookIdIndexRoute,
  SparesCategoryIndexRoute: SparesCategoryIndexRoute,
  SparesCategorySubcategoryComponentTypeRoute:
    SparesCategorySubcategoryComponentTypeRoute,
  SparesCategorySubcategoryIndexRoute: SparesCategorySubcategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
