// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmahwgetrqczytnijbuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtYWh3Z2V0cnFjenl0bmlqYnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTUxNDYsImV4cCI6MjA2ODkzMTE0Nn0.zmC3yOwfW5qw7mRzTt01AiP-xTWUEz7I5zn0Aoieerg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});